name: library

services:
    frontend:
        build: ./frontend
        ports:
            - "8080:80"
        networks:
            - library-network
        depends_on:
            - backend

    backend:
        build: ./backend
        ports:
            - "3000:3000"
        environment:
            - DB_HOST=mariadb
            - DB_USER=root
            - DB_PASSWORD=mysecret
            - DB_NAME=library
        depends_on:
            - mariadb
        networks:
            - library-network

    mariadb:
        image: mariadb:11
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysecret
            MYSQL_DATABASE: keycloak
        volumes:
            - ./db-volume:/var/lib/mysql
        networks:
            - library-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8082:80"
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: mysecret
        networks:
            - library-network

    keycloak:
        image: quay.io/keycloak/keycloak:26.2.5
        command: start-dev
        restart: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: mariadb
            KC_DB_SCHEMA: keycloak
            KC_DB_URL_HOST: mariadb
            KC_DB_USERNAME: root
            KC_DB_PASSWORD: mysecret
        ports:
            - "8081:8080"
        depends_on:
            - mariadb
        networks:
            - library-network

networks:
    library-network: {}
