name: library

services:
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - "8080:80"
        networks:
            - library-network
        depends_on:
            mariadb:
                condition: service_healthy
        image: iru21/library-frontend:latest

    backend:
        container_name: backend
        build: ./backend
        ports:
            - "3000:3000"
        environment:
            - DB_HOST=mariadb
            - DB_USER=root
            - DB_PASSWORD=mysecret
            - DB_NAME=library
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - library-network
        healthcheck:
            test: ["CMD-SHELL", "wget -q --spider http://127.0.0.1:3000/health || exit 1"]
            interval: 10s
            timeout: 5s
            retries: 5
        image: iru21/library-backend:latest

    mariadb:
        container_name: mariadb
        image: mariadb:11
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: mysecret
            MYSQL_DATABASE: keycloak
        volumes:
            - db-volume:/var/lib/mysql
            - ./init-scripts/db.sql:/docker-entrypoint-initdb.d/db.sql
        networks:
            - library-network
        healthcheck:
            test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -u root -pmysecret"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s

    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        ports:
            - "8082:80"
        environment:
            PMA_HOST: mariadb
            PMA_USER: root
            PMA_PASSWORD: mysecret
        networks:
            - library-network
        depends_on:
            mariadb:
                condition: service_healthy

    keycloak:
        container_name: keycloak
        image: quay.io/keycloak/keycloak:26.2.5
        command: start-dev
        restart: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
            KC_DB: mariadb
            KC_DB_SCHEMA: keycloak
            KC_DB_URL_HOST: mariadb
            KC_DB_USERNAME: root
            KC_DB_PASSWORD: mysecret
            KC_HEALTH_ENABLED: true
        ports:
            - "8081:8080"
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - library-network

networks:
    library-network: {}

volumes:
    db-volume:
        driver: local
