apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: library-ingress
    annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
spec:
    rules:
        - host: library.test
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: frontend
                            port:
                                number: 80
                  - path: /api
                    pathType: Prefix
                    backend:
                        service:
                            name: backend
                            port:
                                number: 3000
                  - path: /phpmyadmin
                    pathType: Prefix
                    backend:
                        service:
                            name: phpmyadmin
                            port:
                                number: 8082
        - host: keycloak.test
          http:
              paths:
                  - path: /
                    pathType: Prefix
                    backend:
                        service:
                            name: keycloak
                            port:
                                number: 8081
