apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.36.0 (HEAD)
    labels:
        io.kompose.service: keycloak
    name: keycloak
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: keycloak
    template:
        metadata:
            annotations:
                kompose.cmd: kompose convert -o ./k8s/
                kompose.version: 1.36.0 (HEAD)
            labels:
                io.kompose.service: keycloak
        spec:
            initContainers:
                - command:
                      - sh
                      - -c
                      - |
                          echo "Waiting for mariadb to be ready..."
                            until nc -z mariadb 3306; do
                                sleep 1
                          done
                  image: busybox:latest
                  name: keycloak-wait-for-mariadb
            containers:
                - args:
                      - start
                  env:
                      - name: KC_DB
                        value: mariadb
                      - name: KC_DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                key: mariadb-root-password
                                name: secret
                      - name: KC_DB_SCHEMA
                        value: keycloak
                      - name: KC_DB_URL_HOST
                        value: mariadb
                      - name: KC_DB_USERNAME
                        value: root
                      - name: KC_HEALTH_ENABLED
                        value: "true"
                      - name: KC_PROXY
                        value: edge
                      - name: KC_HTTP_ENABLED
                        value: "true"
                      - name: KC_PROXY_HEADERS
                        value: xforwarded
                      - name: KC_HOSTNAME
                        value: keycloak.test
                  image: quay.io/keycloak/keycloak:26.2.5
                  name: keycloak
                  ports:
                      - containerPort: 8080
                        protocol: TCP
            restartPolicy: Always
