apiVersion: v1
data:
  db.sql: |-
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'mysecret';
    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: mariadb
  name: mariadb-cm1
