apiVersion: v1
data:
    db.sql: |-
        ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysecret';
        ALTER USER 'root'@'%' IDENTIFIED BY 'mysecret';
        GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
        FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
    annotations:
        use-subpath: "true"
    labels:
        io.kompose.service: mariadb
    name: mariadb-cm1
